import { Button, Col, Input, message, Row, Typography } from 'antd'
import StoreBadges from '@/components/StoreBadges'
import { useState } from 'react'
import { ExclamationCircleOutlined } from '@ant-design/icons'
import { actions } from 'mirrorx'


const {Paragraph, Text, Title} = Typography

const MFAConfigPage = (props) => {
    const {me, onCancel, sourcePage} = props
    const [configPage, setConfigPage] = useState(false)
    const [code, setCode] = useState()

    const handleGoback = () => {
        setConfigPage(false)
        onCancel()
    }

    const handleSubmit = () => {
        const payload = {
            user_id: me?.user_id,
            code
        }
        actions.user.verifyMfaCode(payload).then(()=>{
            setCode()
            actions.routing.push(sourcePage ? sourcePage : '/deviceSelection')
        }).catch(()=>{
            message.error('MFA code incorrect, please try again')
        })
    }

    const renderConfig = () => {
        return <>
            <Typography className="text-center">
                <Title level={5}>Let&#39;s set up MFA for you!</Title>
                <Paragraph>
                    <Text strong>Step 1: </Text>Get your smart phone out, and let&#39;s set up an authenticator app! We suggest the Google Authenticator.
                </Paragraph>

                <Row align="middle" justify="center">
                    <StoreBadges
                        googlePlayUrl="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2"
                        appStoreUrl="https://apps.apple.com/app/google-authenticator/id388497605"
                    />
                </Row>

                <Paragraph>
                    <Text strong>Step 2: </Text>Open the app, and scan this QR code:
                </Paragraph>

                <Row align="middle" justify="center">
                    {me?.mfa_qr && <img src={me.mfa_qr}  alt='QR code' className="margin-bottom"/>}
                </Row>

                <Paragraph>
                    <Text>Or alternatively use this setup key instead:</Text><br/>
                    <Text copyable strong>{me?.mfa_secret}</Text>
                </Paragraph>

                <Paragraph style={{display: 'inline-block'}}>
                    <Text strong>Step 3: </Text>Validate! Please type in the code: <Input maxLength={6} style={{ width: 150 }} onChange={e=>setCode(e.target.value)} value={code}/>
                </Paragraph>
            </Typography>
            <Row justify="center" gutter={[20, 20]}>
                <Col>
                    <Button onClick={handleGoback}>Cancel and go back</Button>
                </Col>
                <Col>
                    <Button type="primary" onClick={handleSubmit} disabled={!code}>Validate and Proceed</Button>
                </Col>
            </Row>
        </>
    }

    const renderInfo = () => {
        return <>
            <Typography className="text-center">
                <Text className="exclamation"><ExclamationCircleOutlined /></Text>
                <Title level={5}>Before you can login:</Title>

                <Row justify="center" gutter={[20,20]} style={{marginBottom: '50px'}}>
                    <Col>
                        <Button onClick={handleGoback}>Cancel and go back</Button>
                    </Col>
                    <Col>
                        <Button type="primary" onClick={()=>setConfigPage(true)}>Set up MFA now</Button>
                    </Col>
                </Row>
                <Title type="secondary" level={5}>What is MFA?</Title><br/>
                <Text type="secondary">MFA stands for multi factor authentication, and it&#39;s an extra login step to prove who you are by providing a code to us. This code is valid for 30 seconds or so and is re-generated every 30 seconds. This code is generated by an authenticator app on your phone.</Text>
            </Typography>
        </>
    }

    return(
        configPage? renderConfig() : renderInfo()
    )
}

export default MFAConfigPage
